on:
  push:
  pull_request:
name: Test
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.23.x
          - 1.x
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Start containers
        run: |
          for i in {1..10}; do
            echo $i:
            docker compose -f testdata/docker/compose.yml top | grep 'clamd' && sleep 10 && break || (docker compose -f testdata/docker/compose.yml up -d --force-recreate && sleep 30)
          done
          docker compose -f testdata/docker/compose.yml top
      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
